# Generated by Django 3.1.3 on 2024-04-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeathRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_death', models.DateField()),
                ('place_of_death', models.CharField(max_length=100)),
                ('cause_of_death', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DivorceRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse1_name', models.CharField(max_length=100)),
                ('spouse2_name', models.CharField(max_length=100)),
                ('divorce_date', models.DateField()),
                ('place_of_divorce', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MarriageRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse1_name', models.CharField(max_length=100)),
                ('spouse2_name', models.CharField(max_length=100)),
                ('marriage_date', models.DateField()),
                ('place_of_marriage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MigrationRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('migration_date', models.DateField()),
                ('from_place', models.CharField(max_length=100)),
                ('to_place', models.CharField(max_length=100)),
            ],
        ),
    ]
